# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdmobCocos2dxExample-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AdmobCocos2dxExample-desktop

end

target 'AdmobCocos2dxExample-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AdmobCocos2dxExample-mobile
    pod 'Firebase/Core' 
    pod 'Firebase/AdMob'
end
